@startuml

title Item Lifecycle

state toValidate <<choice>>
state toApprove <<choice>>

[*] --> toValidate : is a valid Item?
toValidate --> rejected : Item is invalid
rejected --> [*]
toValidate -> created : Item is valid

created -> toApprove : is a good Item?
toApprove -> approved : Item approved
approved -> published : Item published

toApprove --> notApproved : Item not approved
notApproved --> closed : Item closed
closed --> [*]

published --> sold : Item sold
sold --> closed : Item closed

@enduml
