@startuml
top to bottom direction
skinparam packageStyle rectangle

actor user
actor buyer
actor seller
actor moderator

user <|-- buyer
user <|-- seller
user <|-- moderator

buyer -- (public-web-app)
seller -- (public-web-app)
moderator -- (moderator-app)
rectangle system {
    (public-web-app) -down-> (public-api)
    (public-api) -down-> (user-service)
    (public-api) -down-> (ads-service)
    (moderator-app) -down-> (ads-service)
    
    rectangle public-api {
    
    }
    
    rectangle public-web-app {
    }

    rectangle ads-service {
    }

    rectangle moderator-app {
    }

    rectangle user-service {
    }
}
@enduml
